CREATE DATABASE BANGLORE;
USE BANGLORE;
CREATE TABLE AREAS(SL_NO INT,NAME varchar(10),LANDMARK varchar(10),PIN_CODE INT,TYPE varchar(12));
 insert into AREAS VALUES (1,'btm','xworkz',524255,'residential');
  insert into AREAS VALUES (2,'jayanagar','WATERTANK',25777,'COMMERCIAL');
   insert into AREAS VALUES (3,'jpnagar','WELL',5242512,'INDUSTRIAL');
    insert into AREAS VALUES (4,'rrnagar','TEMPLE',
    2115,'residential');
     insert into AREAS VALUES (5,'rajajinagr','GROUND',22154154,'POLITICAL');
      insert into AREAS VALUES (6,'vijaynagar','MILK SHOP',2588,'residential');
       insert into AREAS VALUES (7,'indranagr','PG',2588,'residential');
        insert into AREAS VALUES (8,'gandhinagar','JAIDEVA HOSPITAL',524202,'residential');
         insert into AREAS VALUES (9,'shantinagar','KALYANI',401165,'residential');
          insert into AREAS VALUES (10,'banashankari','xworkz',25222,'residential');
          SELECT * FROM AREAS;
SELECT * FROM AREAS order by SL_NO;
SELECT NAME , LANDMARK FROM AREAS order by SL_NO DESC;
select * FROM AREAS WHERE  NAME='vijaynagar' or SL_NO=1 ;
select * from AREAS where sl_no between 10 and 100;
        select * from AREAS where sl_no not in (3 , 6);
