CREATE database EMPLOYEES;
USE EMPLOYEES;
CREATE TABLE DETAILS (SL_NO INT,Name varchar(20),Company varchar(30),Location varchar(10),Salary bigint);
DESC DETAILS;
SELECT * FROM DETAILS;
INSERT INTO DETAILS VALUES(1,'Madhuchandra','Wipro','Whitefield',5);
SELECT * FROM DETAILS;
INSERT INTO DETAILS VALUES(2,'RAGHVENDRA','TCS','Manyat techpark',10);
ALTER TABLE DETAILS MODIFY COLUMN  Location varchar(50);
ALTER TABLE DETAILS RENAME COLUMN Salary TO Salaryin_LPA ;
INSERT INTO DETAILS VALUES(3,'MALTESH','CAPEGEMINI','ELECTRONIC CITY',6);
INSERT INTO DETAILS VALUES(4,'ROHAN','Wipro','Whitefield',12);
INSERT INTO DETAILS VALUES(5,'CHIDANAND','TCS','SARJAPUR',4);
UPDATE DETAILS SET Location='MARATHALLI' WHERE  SL_NO = 3; 
SELECT * FROM DETAILS order by Salaryin_LPA DESC;
SELECT * FROM DETAILS 